# Generated by Django 5.2.17 on 2026-09-06 12:14

import apps.attendance.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.CharField(default=apps.attendance.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Attendance date (one record per user per date)')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_method', models.CharField(choices=[('FACE_RECOGNITION', 'Face Recognition'), ('MANUAL_ADMIN', 'Manual by Admin'), ('SYSTEM', 'System Generated')], default='FACE_RECOGNITION', max_length=20)),
                ('check_in_similarity', models.FloatField(blank=True, help_text='Face recognition similarity score at check-in', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('check_in_confidence', models.CharField(blank=True, default='', max_length=10)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_method', models.CharField(choices=[('FACE_RECOGNITION', 'Face Recognition'), ('MANUAL_ADMIN', 'Manual by Admin'), ('SYSTEM', 'System Generated')], default='FACE_RECOGNITION', max_length=20)),
                ('check_out_similarity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('check_out_confidence', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=10)),
                ('work_hours', models.FloatField(blank=True, help_text='Total work hours (set when employee checks out)', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('admin_override', models.BooleanField(default=False, help_text='Set by admin manually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_3daa40_idx'), models.Index(fields=['date'], name='attendance__date_19baa0_idx'), models.Index(fields=['status'], name='attendance__status_5b1243_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
