# Generated by Django 5.2.17 on 2026-09-06 11:49

import apps.ml_service.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.CharField(default=apps.ml_service.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('embedding', models.JSONField(help_text='512-dimensional face embedding vector')),
                ('quality_score', models.FloatField(help_text='Face quality score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('detection_confidence', models.FloatField(help_text='Face detection confidence score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('estimated_age', models.IntegerField(blank=True, help_text='Estimated age from face analysis', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], help_text='Estimated gender from face analysis', max_length=10, null=True)),
                ('image_width', models.IntegerField(blank=True, help_text='Original image width in pixels', null=True)),
                ('image_height', models.IntegerField(blank=True, help_text='Original image height in pixels', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary embedding for the user')),
                ('registration_source', models.CharField(choices=[('WEB_UPLOAD', 'Web Upload'), ('MOBILE_CAPTURE', 'Mobile Capture'), ('WEBCAM_CAPTURE', 'Webcam Capture'), ('ADMIN_UPLOAD', 'Admin Upload')], default='WEB_UPLOAD', help_text='Source of face registration', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this embedding')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this embedding is active for recognition')),
                ('verified_by_admin', models.BooleanField(default=False, help_text='Whether an admin has verified this face')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this face embedding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'face_embeddings',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='face_embedd_user_id_99ad06_idx'), models.Index(fields=['is_primary'], name='face_embedd_is_prim_35368d_idx'), models.Index(fields=['created_at'], name='face_embedd_created_3ef1b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceRegistrationSession',
            fields=[
                ('id', models.CharField(default=apps.ml_service.models.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('INITIAL', 'Initial Registration'), ('UPDATE', 'Update Existing'), ('RE_ENROLL', 'Re-enrollment')], default='INITIAL', help_text='Type of registration session', max_length=50)),
                ('attempts_count', models.IntegerField(default=0, help_text='Number of capture attempts in this session')),
                ('successful', models.BooleanField(default=False, help_text='Whether the registration was successful')),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Reason for registration failure, if any')),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent string')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User registering their face', on_delete=django.db.models.deletion.CASCADE, related_name='face_registration_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'face_registration_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'successful'], name='face_regist_user_id_9b86c1_idx'), models.Index(fields=['started_at'], name='face_regist_started_d1c1c6_idx')],
            },
        ),
    ]
